src/app/app-routing.module.ts
src/app/app.module.ts
src/app/createorder/createorder.component.ts
src/app/orderdetails/orderdetails.component.ts
src/app/view-orders/order-details-routing.module.ts
src/app/view-orders/order-service.service.ts
src/app/view-orders/order.ts
src/app/view-orders/orderdetails.ts
src/app/view-orders/view-orders.component.ts

https://champlainsaintlambert.atlassian.net/browse/EWCI-12?atlOrigin=eyJpIjoiMmU5OWI4ODNhNDkwNDlmOGFjZTY5MjIxMWQ4ZWZhMGYiLCJwIjoiaiJ9

(ECWI-12) View Order Details

---

src/app/header/header.component.ts
src/app/view-orders/view-orders.component.ts

Added names for selenium tests

Bug/EWCI-0 For selenium test

---

src/app/orderdetails/orderdetails.component.ts
src/app/view-orders/order.ts

I changed the backend a bit so I modified a bit of the details page to make it work again.

conf(EWCI-NULL): Minor Front End Changes

---

src/app/add-order/add-order.component.ts
src/app/view-orders/order.ts

Added a small routing for submit button

feat(EWCI-NULL): Routed Submit to list

---

src/app/add-order/add-order.component.ts

Bug(EWCI-21) Create Order Navigation Bug

---

src/app/view-orders/view-orders.component.ts

Small change for selenium testing, added names to td elements.

feat(EWCI-13): Small change for Selenium

---

angular.json
package-lock.json
package.json
src/app/add-order/add-order.component.ts
src/app/app.module.ts
src/app/update-order/update-order.component.ts
src/app/view-orders/order-service.service.ts
src/app/view-orders/view-orders.component.ts
src/index.html
src/styles.scss

JIRA: https://champlainsaintlambert.atlassian.net/browse/EWCI-14?atlOrigin=eyJpIjoiZjFhOTUzODE5NjUxNGViNjlhMTQ3YjAyMjFkNmZjZjUiLCJwIjoiaiJ9
Description: Get all orders that are active/cancelled/all according to their status.

Feat(EWCI-14) View Active/Cancelled/All orders

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/contact/contact.component.ts
src/app/header/header.component.ts
src/app/login/login.component.ts

JIRA 1: https://champlainsaintlambert.atlassian.net/browse/EWCI-24?atlOrigin=eyJpIjoiZjRmMjI0MThjOWE0NDA3ZmFhZDI5ZjQ3MGFmYWU0YWUiLCJwIjoiaiJ9
JIRA 2: https://champlainsaintlambert.atlassian.net/browse/EWCI-25?atlOrigin=eyJpIjoiMTU3MzNmN2VhMmYzNDMwYmFmYWVjNDQxYzA0ODkyNjgiLCJwIjoiaiJ9
UI Changes: Added an informational contact page in the UI so customers know which email and phone to reach if they have concerns. 
Linked PRs: None

feat(EWCI-24, EWCI-25): Contact page including company phone and email

---

src/app/add-order/add-order.component.ts

JIRA: https://champlainsaintlambert.atlassian.net/browse/EWCI-48?atlOrigin=eyJpIjoiNmFmOTUzNTE5NjQ5NDJkNWJmMzUxMjE3MjQxYjM1YTYiLCJwIjoiaiJ9
UI Changes: Removed order id, tracking number, status and design fields in the order cabinet form
Linked PRs: https://github.com/VladPopa616/wondacabinetinc/pull/17
Dev notes: None

feat(EWCI-48):Removed Id, status, design and Tracking Number fields when adding an order

---

src/app/add-order/add-order.component.ts
src/app/orderdetails/orderdetails.component.ts
src/app/view-orders/order-service.service.ts
src/app/view-orders/order.ts
src/app/view-orders/view-orders.component.ts
tsconfig.json

JIRA: https://champlainsaintlambert.atlassian.net/browse/EWCI-29?atlOrigin=eyJpIjoiNDU2MTg3NmVjNDZiNDgwMGIwMmFmYjU5NzA0YmE2OGIiLCJwIjoiaiJ9
UI CHANGES: Changed tables to display by customer email for the customer point of view instead of seeing everything. Now only employees can see everything. 
Linked PRs: https://github.com/VladPopa616/wondacabinetinc/pull/20

feat(EWCI-29): Set Email Filter For Customers

---

src/app/login/login.component.ts

JIRA: https://champlainsaintlambert.atlassian.net/browse/EWCI-60?atlOrigin=eyJpIjoiZWQwMzk5YTlkZjA2NDhiNTg0NThhMmI3OTBjNGNjZmIiLCJwIjoiaiJ9
UI Changes: Login form will not validate for password length anymore
Linked PRs: None

bug(EWCI-60): Login Password Validation Removed

---

package-lock.json
package.json
src/app/app.module.ts
src/app/delete-order/delete-order.component.ts
src/app/delete-password/delete-password.component.ts
src/app/login/login.service.ts
src/app/view-orders/order-service.service.ts
src/app/view-orders/view-orders.component.ts
src/styles.scss

JIRA: https://champlainsaintlambert.atlassian.net/browse/EWCI-16?atlOrigin=eyJpIjoiMDI5NDVmOWY5NTgzNGFjM2E0ZDY5MjNiZGMzNjBhZDciLCJwIjoiaiJ9
Changes: Added password validation before deleting order.

Feat(EWCI-16) Delete order from database

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/delete-order/delete-order.component.ts
src/app/delete-password/delete-password.component.ts
src/app/header/header.component.ts
src/app/view-order-with-tracking-no/view-order-with-tracking-no.component.ts
src/app/view-orders/order-service.service.ts
src/app/view-orders/order.ts
src/app/view-orders/view-orders.component.ts
src/styles.scss

JIRA: https://champlainsaintlambert.atlassian.net/browse/EWCI-57?atlOrigin=eyJpIjoiNTE2MTNhOGY0OGQ2NDUxYzhlYzU5OWE1MjIwNDFmMzkiLCJwIjoiaiJ9
Changes:

Feat(EWCI-57) Look up order as guest

---

src/app/_auth/auth.interceptor.ts
src/app/add-order/add-order.component.ts
src/app/delete-password/delete-password.component.ts
src/app/login/event.class.ts
src/app/login/eventbus.service.ts
src/app/login/login.component.ts
src/app/login/login.service.ts
src/app/login/tokenstorage.service.ts
src/app/view-orders/view-orders.component.ts

JIRA: https://champlainsaintlambert.atlassian.net/browse/EWCI-64?atlOrigin=eyJpIjoiM2Y0YWY5NGViMTEwNDA1MDg3NDJkYTI3ODg4NGRiYzUiLCJwIjoiaiJ9
UI Changes: Refresh token will be administered through Auth Interceptor and change authorization header for new provided JWT token. When Refresh Token expires, it will log out the user. 
Linked PRs: https://github.com/VladPopa616/wondacabinetinc/pull/24

feat(EWCI-64): Refresh Token

---

src/app/add-order/add-order.component.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/footer/footer.component.ts
src/app/header/header.component.ts
src/app/home/home.component.ts
src/app/view-order-with-tracking-no/view-order-with-tracking-no.component.ts
src/app/view-orders/view-orders.component.ts
src/styles.scss

JIRA: https://champlainsaintlambert.atlassian.net/browse/EWCI-63?atlOrigin=eyJpIjoiNWNlYzdhODEzY2Y0NGExZDkxZDFiYmRiYmY2YTI0ZWUiLCJwIjoiaiJ9
Changes:

Feat(EWCI-63) Styling

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/forgotpassword/forgotpassword.component.ts
src/app/login/login.component.ts
src/app/login/login.service.ts

JIRA: https://champlainsaintlambert.atlassian.net/browse/EWCI-26?atlOrigin=eyJpIjoiOGRlMzllNmIzZTIzNDJlMTlkZTczMmU3NDRlYjhhMjYiLCJwIjoiaiJ9
Changes: Added UI for forgot password Functionality
Enter user email to send token 
Confirmation of email sent
Email with token
Enter new password and token to reset password
Confirmation of password reset
Linked PRs: https://github.com/VladPopa616/wondacabinetinc/pull/29

feat(EWCI-26): Forgot Password

---

package-lock.json
package.json
src/app/add-order/add-order.component.ts
src/app/app.module.ts
src/app/date-time-picker/date-time-picker.component.ts
src/app/header/header.component.ts
src/app/orderdetails/orderdetails.component.ts
src/app/update-order/update-order.component.ts
src/app/view-order-with-tracking-no/view-order-with-tracking-no.component.ts
src/app/view-orders/order-service.service.ts
src/app/view-orders/order.ts
src/app/view-orders/view-orders.component.ts
src/styles.scss

JIRA: https://champlainsaintlambert.atlassian.net/browse/EWCI-31?atlOrigin=eyJpIjoiZmJmMThjOTBkNmJiNDkwNjllNWY1ZWRmMTYxMWFkYTIiLCJwIjoiaiJ9
https://champlainsaintlambert.atlassian.net/browse/EWCI-32?atlOrigin=eyJpIjoiYzlkOTIxMmNjNTQ1NGYyZGE3ODNiNjRkNzgzYzk4ZWIiLCJwIjoiaiJ9
**
**

Feat(EWCI-31-32) Schedule Delivery

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/cancelrequest/cancelrequest.component.ts
src/app/forgotpassword/forgotpassword.component.ts
src/app/header/header.component.ts
src/app/updaterequest/updaterequest.component.ts
src/app/view-orders/order-service.service.ts
src/styles.scss

JIRA 1: https://champlainsaintlambert.atlassian.net/browse/EWCI-9?atlOrigin=eyJpIjoiMmNhMmM5NDMxMmY2NGI2NWJhNzNmYjBlODM0NzlhMjEiLCJwIjoiaiJ9
JIRA 2: https://champlainsaintlambert.atlassian.net/browse/EWCI-8?atlOrigin=eyJpIjoiZWJjMDNlNWFkZDNlNDc5ODhlMTcxOTEzOGQyYTI0NjQiLCJwIjoiaiJ9
Changes: 
Update Request UI
Cancel Request UI
Confirmation on both when submitted
Linked PRs: https://github.com/VladPopa616/wondacabinetinc/pull/30

feat(EWCI-8, EWCI-9) Update and Cancel Requests

---

src/app/contact/contact.component.ts
src/app/delete-password/delete-password.component.ts
src/app/header/header.component.ts
src/app/login/login.component.ts
src/app/update-order/update-order.component.ts
src/app/view-orders/view-orders.component.ts

Changes: Tracking number for email part from long to string

Bug(EWCI-00) Tracking number type from long to string

---

package-lock.json
package.json
src/app/app.module.ts
src/app/header/header.component.ts

Readded responsiveness to the header because it was removed during an update of the UI.

Bug(EWCI-Null) Header Responsiveness readded

---

src/app/header/header.component.ts

Mobile responsiveness readded after the UI update

Bug(EWCi-Null) Icons for responsiveness 

---

src/app/header/header.component.ts

Reverts LawrenceLiang02/WondaCabinetInc_FrontEnd#30

Revert "Bug(EWCi-Null) Icons for responsiveness "
